version: "3.8"

services:
  payment-intermediator-api-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-intermediator-api-1
    hostname: payment-intermediator-1
    ports:
      - "9997:9999"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "225MB"
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - DATABASE_DSN=postgres://postgres:postgres@db:5432/rinha?sslmode=disable
    networks:
      - backend
      - payment-processor
    depends_on:
      - db

  payment-intermediator-api-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-intermediator-api-2
    hostname: payment-intermediator-2
    ports:
      - "9998:9999"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "225MB"
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - DATABASE_DSN=postgres://postgres:postgres@db:5432/rinha?sslmode=disable
    networks:
      - backend
      - payment-processor
    depends_on:
      - db

  nginx:
    image: nginx:latest
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"
    networks:
      - backend
    depends_on:
      - payment-intermediator-api-1
      - payment-intermediator-api-2
    restart: on-failure

  db:
    image: postgres:15.2-alpine
    hostname: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "180MB"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
