version: "3.9"

services:
  #--- LOAD BALANCER ---
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

  api1: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api1
    environment:
      - PORT=8080
      - DATABASE_DSN=postgres://postgres:postgres@db:5432/rinha?sslmode=disable
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - HEALTH_CHECK_INTERVAL=10
      - HTTP_TIMEOUT=5
      - MAX_CONCURRENT=1000
    networks:
      - rinha-net
      - payment-processor-net
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - PORT=8080
      - DATABASE_DSN=postgres://postgres:postgres@db:5432/rinha?sslmode=disable
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - HEALTH_CHECK_INTERVAL=10
      - HTTP_TIMEOUT=5
      - MAX_CONCURRENT=1000

  #--- DATABASE ---
  db:
    image: postgres:15.2-alpine
    hostname: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "200MB"
    networks:
      - rinha-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

#--- NETWORKS ---
networks:
  rinha-net:
    driver: bridge
  payment-processor-net:
    name: payment-processor
    external: true
